-- Suppression des tables existantes avec toutes les contraintes associées
DROP TABLE tp_statistique CASCADE CONSTRAINTS;
DROP TABLE tp_type_statistique CASCADE CONSTRAINTS;
DROP TABLE tp_equipement CASCADE CONSTRAINTS;
DROP TABLE tp_type_equipement CASCADE CONSTRAINTS;
DROP TABLE tp_match CASCADE CONSTRAINTS;
DROP TABLE tp_entrainement CASCADE CONSTRAINTS;
DROP TABLE tp_joueur CASCADE CONSTRAINTS;
DROP TABLE tp_lieu CASCADE CONSTRAINTS;
DROP TABLE tp_equipe CASCADE CONSTRAINTS;
DROP TABLE tp_defenseur CASCADE CONSTRAINTS;
DROP TABLE tp_gardien CASCADE CONSTRAINTS;
DROP TABLE tp_attaquant CASCADE CONSTRAINTS;
DROP TABLE tp_position CASCADE CONSTRAINTS;

-- Création des tables avec les contraintes
CREATE TABLE tp_position
(
    pos_id  INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    pos_nom VARCHAR2(255) NOT NULL
);

CREATE TABLE tp_defenseur
(
    def_position_id INT PRIMARY KEY,
    def_placement   VARCHAR2(255),
    CONSTRAINT fk_defenseur_position FOREIGN KEY (def_position_id) REFERENCES tp_position (pos_id)
);

CREATE TABLE tp_gardien
(
    gar_position_id INT PRIMARY KEY,
    CONSTRAINT fk_gardien_position FOREIGN KEY (gar_position_id) REFERENCES tp_position (pos_id)
);

CREATE TABLE tp_attaquant
(
    att_position_id INT PRIMARY KEY,
    att_placement   VARCHAR2(255),
    CONSTRAINT fk_attaquant_position FOREIGN KEY (att_position_id) REFERENCES tp_position (pos_id)
);

CREATE TABLE tp_equipe
(
    equ_id  INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    equ_nom VARCHAR2(255) NOT NULL
);

CREATE TABLE tp_joueur
(
    jou_id              INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    jou_nom             VARCHAR2(255) NOT NULL,
    jou_annee_naissance DATE,
    jou_numero_maillot  INT,
    jou_position_id     INT,
    jou_equipe_id       INT,
    CONSTRAINT fk_joueur_position FOREIGN KEY (jou_position_id) REFERENCES tp_position (pos_id),
    CONSTRAINT fk_joueur_equipe FOREIGN KEY (jou_equipe_id) REFERENCES tp_equipe (equ_id)
);

CREATE TABLE tp_lieu
(
    lie_id  INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    lie_nom VARCHAR2(255) NOT NULL
);

CREATE TABLE tp_match
(
    mat_id                   INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    mat_date_match           DATE NOT NULL,
    mat_score_final          VARCHAR2(255),
    mat_equipe_local_id      INT,
    mat_equipe_adversaire_id INT,
    mat_lieu_id              INT,
    CONSTRAINT fk_match_equipe_local FOREIGN KEY (mat_equipe_local_id) REFERENCES tp_equipe (equ_id),
    CONSTRAINT fk_match_equipe_adversaire FOREIGN KEY (mat_equipe_adversaire_id) REFERENCES tp_equipe (equ_id),
    CONSTRAINT fk_match_lieu FOREIGN KEY (mat_lieu_id) REFERENCES tp_lieu (lie_id)
);

CREATE TABLE tp_entrainement
(
    ent_id                INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ent_date_entrainement TIMESTAMP NOT NULL,
    ent_lieu_id           INT,
    CONSTRAINT fk_entrainement_lieu FOREIGN KEY (ent_lieu_id) REFERENCES tp_lieu (lie_id)
);

CREATE TABLE tp_type_equipement
(
    tye_id          INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    tye_nom         VARCHAR2(255) NOT NULL,
    tye_description VARCHAR2(2000)
);

CREATE TABLE tp_equipement
(
    equ_id                 INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    equ_nom                VARCHAR2(255) NOT NULL,
    equ_description        CLOB,
    equ_quantite           INT,
    equ_etat               VARCHAR2(255),
    equ_type_equipement_id INT,
    equ_joueur_id          INT DEFAULT NULL,
    CONSTRAINT fk_equipement_type_equipement FOREIGN KEY (equ_type_equipement_id) REFERENCES tp_type_equipement (tye_id),
    CONSTRAINT fk_equipement_joueur FOREIGN KEY (equ_joueur_id) REFERENCES tp_joueur (jou_id)
);

CREATE TABLE tp_type_statistique
(
    tys_id          INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    tys_nom         VARCHAR2(255) NOT NULL,
    tys_description VARCHAR2(2000)
);

CREATE TABLE tp_statistique
(
    sta_id                  INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    sta_joueur_id           INT,
    sta_match_id            INT,
    sta_valeur              INT,
    sta_type_statistique_id INT,
    CONSTRAINT fk_statistique_joueur FOREIGN KEY (sta_joueur_id) REFERENCES tp_joueur (jou_id),
    CONSTRAINT fk_statistique_match FOREIGN KEY (sta_match_id) REFERENCES tp_match (mat_id),
    CONSTRAINT fk_statistique_type_statistique FOREIGN KEY (sta_type_statistique_id) REFERENCES tp_type_statistique (tys_id)
);

-- Insertion des données initiales dans les tables
-- Insertion des positions
INSERT INTO tp_position (pos_nom)
VALUES ('Défenseur');
INSERT INTO tp_position (pos_nom)
VALUES ('Gardien');
INSERT INTO tp_position (pos_nom)
VALUES ('Attaquant');

-- Insertion des défenseurs, gardiens et attaquants avec leurs placements
INSERT INTO tp_defenseur (def_position_id, def_placement)
VALUES (1, 'Gauche');
INSERT INTO tp_gardien (gar_position_id)
VALUES (2);
INSERT INTO tp_attaquant (att_position_id, att_placement)
VALUES (3, 'Droit');

-- Insertion des équipes
INSERT INTO tp_equipe (equ_nom)
VALUES ('Équipe Bleue');
INSERT INTO tp_equipe (equ_nom)
VALUES ('Équipe Rouge');
INSERT INTO tp_equipe (equ_nom)
VALUES ('Équipe Verte');
INSERT INTO tp_equipe (equ_nom)
VALUES ('Équipe Jaune');
INSERT INTO tp_equipe (equ_nom)
VALUES ('Équipe Noire');
INSERT INTO tp_equipe (equ_nom)
VALUES ('Équipe Blanche');

-- Insertion des joueurs
INSERT INTO tp_joueur (jou_nom, jou_annee_naissance, jou_numero_maillot, jou_position_id, jou_equipe_id)
VALUES ('Alice Martin', TO_DATE('2000-04-25', 'yyyy-MM-dd'), 9, 1, 1);
INSERT INTO tp_joueur (jou_nom, jou_annee_naissance, jou_numero_maillot, jou_position_id, jou_equipe_id)
VALUES ('Bob Léger', TO_DATE('1991-06-22', 'yyyy-MM-dd'), 1, 2, 2);
INSERT INTO tp_joueur (jou_nom, jou_annee_naissance, jou_numero_maillot, jou_position_id, jou_equipe_id)
VALUES ('Carla Diaz', TO_DATE('1999-02-13', 'yyyy-MM-dd'), 7, 3, 3);
INSERT INTO tp_joueur (jou_nom, jou_annee_naissance, jou_numero_maillot, jou_position_id, jou_equipe_id)
VALUES ('Théo Cartier', TO_DATE('1980-02-13', 'yyyy-MM-dd'), 8, 3, 3);
INSERT INTO tp_joueur (jou_nom, jou_annee_naissance, jou_numero_maillot, jou_position_id, jou_equipe_id)
VALUES ('Théo TruncAvecUnC', TO_DATE('1980-02-13', 'yyyy-MM-dd'), 8, 3, 3);
INSERT INTO tp_joueur (jou_nom, jou_annee_naissance, jou_numero_maillot, jou_position_id, jou_equipe_id)
VALUES ('Simon ElContradiction', TO_DATE('2000-02-13', 'yyyy-MM-dd'), 10, 3, 2);
INSERT INTO tp_joueur (jou_nom, jou_annee_naissance, jou_numero_maillot, jou_position_id, jou_equipe_id)
VALUES ('David Renault', TO_DATE('2002-05-14', 'yyyy-MM-dd'), 5, 1, 4);
INSERT INTO tp_joueur (jou_nom, jou_annee_naissance, jou_numero_maillot, jou_position_id, jou_equipe_id)
VALUES ('Emma Dubois', TO_DATE('1995-03-10', 'yyyy-MM-dd'), 6, 2, 4);
INSERT INTO tp_joueur (jou_nom, jou_annee_naissance, jou_numero_maillot, jou_position_id, jou_equipe_id)
VALUES ('Fabien Laurent', TO_DATE('1988-07-30', 'yyyy-MM-dd'), 11, 3, 5);
INSERT INTO tp_joueur (jou_nom, jou_annee_naissance, jou_numero_maillot, jou_position_id, jou_equipe_id)
VALUES ('Gisèle Dupont', TO_DATE('2001-11-21', 'yyyy-MM-dd'), 3, 1, 6);
INSERT INTO tp_joueur (jou_nom, jou_annee_naissance, jou_numero_maillot, jou_position_id, jou_equipe_id)
VALUES ('Henri Moreau', TO_DATE('1993-09-15', 'yyyy-MM-dd'), 4, 3, 1);
INSERT INTO tp_joueur (jou_nom, jou_annee_naissance, jou_numero_maillot, jou_position_id, jou_equipe_id)
VALUES ('Isabelle Lefevre', TO_DATE('1985-08-25', 'yyyy-MM-dd'), 12, 2, 2);

-- Insertion des lieux
INSERT INTO tp_lieu (lie_nom)
VALUES ('Stade Central');
INSERT INTO tp_lieu (lie_nom)
VALUES ('Aréna Nord');
INSERT INTO tp_lieu (lie_nom)
VALUES ('Complexe Sportif Sud');
INSERT INTO tp_lieu (lie_nom)
VALUES ('Gymnase Ouest');
INSERT INTO tp_lieu (lie_nom)
VALUES ('Parc des Sports');
INSERT INTO tp_lieu (lie_nom)
VALUES ('Hall des Champions');

-- Insertion des matchs
INSERT INTO tp_match (mat_date_match, mat_score_final, mat_equipe_local_id, mat_equipe_adversaire_id, mat_lieu_id)
VALUES (DATE '2024-04-15', '3-2', 1, 2, 1);
INSERT INTO tp_match (mat_date_match, mat_score_final, mat_equipe_local_id, mat_equipe_adversaire_id, mat_lieu_id)
VALUES (DATE '2024-04-20', '1-1', 2, 3, 2);
INSERT INTO tp_match (mat_date_match, mat_score_final, mat_equipe_local_id, mat_equipe_adversaire_id, mat_lieu_id)
VALUES (DATE '2024-04-25', '4-3', 1, 3, 3);
INSERT INTO tp_match (mat_date_match, mat_score_final, mat_equipe_local_id, mat_equipe_adversaire_id, mat_lieu_id)
VALUES (DATE '2024-05-05', '2-2', 4, 5, 4);
INSERT INTO tp_match (mat_date_match, mat_score_final, mat_equipe_local_id, mat_equipe_adversaire_id, mat_lieu_id)
VALUES (DATE '2024-05-10', '1-0', 6, 1, 5);
INSERT INTO tp_match (mat_date_match, mat_score_final, mat_equipe_local_id, mat_equipe_adversaire_id, mat_lieu_id)
VALUES (DATE '2024-05-15', '3-3', 2, 4, 6);

-- Insertion des entraînements
INSERT INTO tp_entrainement (ent_date_entrainement)
VALUES (TO_DATE('2024-05-01 19:00:00', 'yyyy-MM-dd hh24:mi:ss'));
INSERT INTO tp_entrainement (ent_date_entrainement)
VALUES (TO_DATE('2024-05-02 18:00:00', 'yyyy-mm-dd hh24:mi:ss'));
INSERT INTO tp_entrainement (ent_date_entrainement)
VALUES (TO_DATE('2024-05-03 19:00:00', 'yyyy-MM-dd hh24:mi:ss'));
INSERT INTO tp_entrainement (ent_date_entrainement)
VALUES (TO_DATE('2024-05-04 17:00:00', 'yyyy-MM-dd hh24:mi:ss'));
INSERT INTO tp_entrainement (ent_date_entrainement)
VALUES (TO_DATE('2024-05-05 18:30:00', 'yyyy-mm-dd hh24:mi:ss'));
INSERT INTO tp_entrainement (ent_date_entrainement)
VALUES (TO_DATE('2024-05-06 19:00:00', 'yyyy-MM-dd hh24:mi:ss'));

-- Insertion des types d'équipements
INSERT INTO tp_type_equipement (tye_nom, tye_description)
VALUES ('Maillot', 'Maillot officiel de l''équipe');
INSERT INTO tp_type_equipement (tye_nom, tye_description)
VALUES ('Casque', 'Casque de protection homologué');
INSERT INTO tp_type_equipement (tye_nom, tye_description)
VALUES ('Patins', 'Patins de hockey sur glace haute performance');
INSERT INTO tp_type_equipement (tye_nom, tye_description)
VALUES ('Gants', 'Gants de protection pour joueurs');
INSERT INTO tp_type_equipement (tye_nom, tye_description)
VALUES ('Protège-tibias', 'Protège-tibias homologués pour la compétition');

-- Insertion des équipements
INSERT INTO tp_equipement (equ_nom, equ_description, equ_quantite, equ_etat, equ_type_equipement_id, equ_joueur_id)
VALUES ('Maillot #9', 'Maillot bleu', 30, 'Neuf', 1, 1);
INSERT INTO tp_equipement (equ_nom, equ_description, equ_quantite, equ_etat, equ_type_equipement_id, equ_joueur_id)
VALUES ('Casque Bleu', 'Casque de sécurité', 15, 'Usé', 2, 2);
INSERT INTO tp_equipement (equ_nom, equ_description, equ_quantite, equ_etat, equ_type_equipement_id, equ_joueur_id)
VALUES ('Patins Rapides', 'Patins taille 42', 20, 'Neuf', 3, 3);
INSERT INTO tp_equipement (equ_nom, equ_description, equ_quantite, equ_etat, equ_type_equipement_id, equ_joueur_id)
VALUES ('Gants de Gardien', 'Gants taille L', 10, 'Neuf', 4, 2);
INSERT INTO tp_equipement (equ_nom, equ_description, equ_quantite, equ_etat, equ_type_equipement_id, equ_joueur_id)
VALUES ('Protège-tibias Pro', 'Protège-tibias taille M', 25, 'Bon', 5, 3);
INSERT INTO tp_equipement (equ_nom, equ_description, equ_quantite, equ_etat, equ_type_equipement_id, equ_joueur_id)
VALUES ('Maillot #10', 'Maillot rouge', 40, 'Neuf', 1, 4);

-- Insertion des types de statistiques
INSERT INTO tp_type_statistique (tys_nom, tys_description)
VALUES ('Buts', 'Nombre de buts marqués');
INSERT INTO tp_type_statistique (tys_nom, tys_description)
VALUES ('Passes', 'Nombre de passes décisives');
INSERT INTO tp_type_statistique (tys_nom, tys_description)
VALUES ('Pénalités', 'Minutes de pénalité');
INSERT INTO tp_type_statistique (tys_nom, tys_description)
VALUES ('Arrêts', 'Nombre d''arrêts effectués par le gardien');
INSERT INTO tp_type_statistique (tys_nom, tys_description)
VALUES ('Tirs', 'Nombre de tirs effectués');

-- Insertion des statistiques
INSERT INTO tp_statistique (sta_joueur_id, sta_match_id, sta_valeur, sta_type_statistique_id)
VALUES (5, 1, 30, 1);
INSERT INTO tp_statistique (sta_joueur_id, sta_match_id, sta_valeur, sta_type_statistique_id)
VALUES (6, 2, 30, 1);
INSERT INTO tp_statistique (sta_joueur_id, sta_match_id, sta_valeur, sta_type_statistique_id)
VALUES (7, 3, 3, 1);
INSERT INTO tp_statistique (sta_joueur_id, sta_match_id, sta_valeur, sta_type_statistique_id)
VALUES (8, 4, 30, 4);
INSERT INTO tp_statistique (sta_joueur_id, sta_match_id, sta_valeur, sta_type_statistique_id)
VALUES (9, 5, 30, 1);
INSERT INTO tp_statistique (sta_joueur_id, sta_match_id, sta_valeur, sta_type_statistique_id)
VALUES (12, 6, 46, 4);
INSERT INTO tp_statistique (sta_joueur_id, sta_match_id, sta_valeur, sta_type_statistique_id)
VALUES (1, 1, 2, 1);
INSERT INTO tp_statistique (sta_joueur_id, sta_match_id, sta_valeur, sta_type_statistique_id)
VALUES (3, 2, 2, 1);
INSERT INTO tp_statistique (sta_joueur_id, sta_match_id, sta_valeur, sta_type_statistique_id)
VALUES (4, 3, 2, 1);
INSERT INTO tp_statistique (sta_joueur_id, sta_match_id, sta_valeur, sta_type_statistique_id)
VALUES (3, 4, 2, 1);
INSERT INTO tp_statistique (sta_joueur_id, sta_match_id, sta_valeur, sta_type_statistique_id)
VALUES (4, 5, 2, 1);
INSERT INTO tp_statistique (sta_joueur_id, sta_match_id, sta_valeur, sta_type_statistique_id)
VALUES (2, 2, 3, 2);
INSERT INTO tp_statistique (sta_joueur_id, sta_match_id, sta_valeur, sta_type_statistique_id)
VALUES (6, 4, 3, 4);
INSERT INTO tp_statistique (sta_joueur_id, sta_match_id, sta_valeur, sta_type_statistique_id)
VALUES (7, 5, 1, 5);
INSERT INTO tp_statistique (sta_joueur_id, sta_match_id, sta_valeur, sta_type_statistique_id)
VALUES (10, 2, 5, 4);
INSERT INTO tp_statistique (sta_joueur_id, sta_match_id, sta_valeur, sta_type_statistique_id)
VALUES (11, 3, 6, 5);
INSERT INTO tp_statistique (sta_joueur_id, sta_match_id, sta_valeur, sta_type_statistique_id)
VALUES (3, 3, 10, 3);
INSERT INTO tp_statistique (sta_joueur_id, sta_match_id, sta_valeur, sta_type_statistique_id)
VALUES (1, 3, 10, 3);
INSERT INTO tp_statistique (sta_joueur_id, sta_match_id, sta_valeur, sta_type_statistique_id)
VALUES (4, 3, 1, 1);
INSERT INTO tp_statistique (sta_joueur_id, sta_match_id, sta_valeur, sta_type_statistique_id)
VALUES (9, 1, 2, 2);
INSERT INTO tp_statistique (sta_joueur_id, sta_match_id, sta_valeur, sta_type_statistique_id)
VALUES (12, 4, 7, 4);


-- Commit des données insérées
COMMIT;

-- Requête pour afficher les joueurs avec leurs statistiques
SELECT j.jou_numero_maillot,
       CASE
           WHEN p.pos_id IS NULL THEN 'N/A'
           WHEN p.pos_id = d.def_position_id THEN p.pos_nom || ' ' || d.def_placement
           WHEN p.pos_id = g.gar_position_id THEN p.pos_nom
           WHEN p.pos_id = a.att_position_id THEN p.pos_nom || ' ' || a.att_placement
           END                                                                       AS placement,
       j.jou_nom,
       TO_CHAR(TRUNC(MONTHS_BETWEEN(SYSDATE, j.jou_annee_naissance) / 12)) || ' ans' AS age,
       ts.tys_nom                                                                    AS statistique,
       s.sta_valeur                                                                  AS valeur_statistique
FROM tp_joueur j
         LEFT JOIN tp_statistique s ON j.jou_id = s.sta_joueur_id
         LEFT JOIN tp_type_statistique ts ON ts.tys_id = s.sta_type_statistique_id
         LEFT JOIN tp_position p ON p.pos_id = j.jou_position_id
         LEFT JOIN tp_defenseur d ON d.def_position_id = p.pos_id
         LEFT JOIN tp_gardien g ON g.gar_position_id = p.pos_id
         LEFT JOIN tp_attaquant a ON a.att_position_id = p.pos_id;

-- Requête pour afficher le nombre de buts par position
SELECT p.pos_nom AS "Position", SUM(s.sta_valeur) AS "Nombre but"
FROM tp_joueur j
         LEFT JOIN tp_statistique s ON j.jou_id = s.sta_joueur_id
         LEFT JOIN tp_type_statistique ts ON ts.tys_id = s.sta_type_statistique_id
         LEFT JOIN tp_position p ON p.pos_id = j.jou_position_id
         LEFT JOIN tp_defenseur d ON d.def_position_id = p.pos_id
         LEFT JOIN tp_gardien g ON g.gar_position_id = p.pos_id
         LEFT JOIN tp_attaquant a ON a.att_position_id = p.pos_id
WHERE LOWER(ts.tys_nom) = 'buts'
GROUP BY p.pos_nom
ORDER BY "Nombre but" DESC;